version: "3.7"
services:
  app:
    build:
      context: .
      target: base
    tty: true
    stdin_open: true
    volumes:
      - .:/src
    ports:
      - 8080:8080
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
